### ISSUE TITLE
Add unit tests for the inventory service

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/point-of-sale#91]
### Description
- Inventory service requires unit tests
   - Controller class
   - Connector for Database
   - Connector for InMemory

**Comment by bourgeoisor** [comment]
I think we should still do this -- reseting SLO.

**Comment by NimJay** [comment]
Comment because this is near out-of-SLO:
* Please see [my comment in #94 (issue about adding unit tests for the Payment service)](https://github.com/GoogleCloudPlatform/point-of-sale/issues/94#issuecomment-1777294181).
* I feel the same way about this issue — our team cannot afford granular unit tests. We should rely on high-level/integration/end-to-end tests instead.
